# Commands to start on workspace startup
tasks:
  - init: npm install
  - name: TypeScript Compiler
  - command:
      npm run watch
  - name: Editor Server
    command: npm run editor-remote
# Ports to expose on workspace startup
ports:
  - port: 1959
    onOpen: open-preview